version: '3.9'

services:
  miner:
    build: .
    container_name: bitcoin_miner
    volumes:
      - .:/app
      - output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  output:
